@startuml
|AssignEventCommand|
start
:Check if event exists;
if (Event exists?) then (yes)
  :Get Event from model;
else (no)
  :Return CommandResult "Event not found";
  stop
endif

:Check if roles are specified;
if (Roles are specified?) then (yes)
  :Check if roles exist in the event;
  if (Roles exist?) then (yes)
  else (no)
    :             Return CommandResult
    \n"Roles not found under specified Event";
    stop
  endif
else (no)
endif

:Check if member exists;
if (Member exists?) then (yes)
  :Get Member from model;
else (no)
  :          Return CommandResult \n"Member not found in event roster";
  stop
endif

:Check if member is already in event roster;
if (Member already exists?) then (yes)
  :Throw CommandException "Member already exists in event roster";
  stop
else (no)
endif

:Handle if no event roles specified;
if (Roles are specified?) then (no)
  :Add "Participant" to member's event roles list;
  else (yes)
  :Add specified event roles to member;

endif

:Add member to event roster;
:Update model with new event and member info;

:Return success CommandResult;
stop
@enduml
