@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ClubBook Storage" #F4F6F6{
Class "<<interface>>\nClubBookStorage" as ClubBookStorage
Class JsonClubBookStorage
Class JsonSerializableClubBook
Class JsonAdaptedMember
Class JsonAdaptedEvent
Class JsonAdaptedEventRole
Class JsonAdaptedMemberRole
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ClubBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ClubBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonClubBookStorage .up.|> ClubBookStorage
JsonClubBookStorage ..> JsonSerializableClubBook
JsonSerializableClubBook --> "*" JsonAdaptedMember
JsonSerializableClubBook --> "*" JsonAdaptedEvent
JsonAdaptedEvent --> "*" JsonAdaptedEventRole
JsonAdaptedEvent --> "*" JsonAdaptedMember
JsonAdaptedMember --> "*" JsonAdaptedMemberRole
JsonAdaptedMember --> "*" JsonAdaptedEventRole



@enduml
