@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR


package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class MemberListPanel
Class MemberCard
Class EventListPanel
Class EventCard
Class SingleEventPanel
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" MemberListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow
MainWindow *-down-> "1" EventListPanel
MainWindow *-down-> "1" SingleEventPanel

MemberListPanel -down-> "*" MemberCard
EventListPanel -down-> "*" EventCard

MainWindow --|> UiPart

ResultDisplay -up-|> UiPart
CommandBox -up-|> UiPart
MemberListPanel --|> UiPart
MemberCard -left-|> UiPart
EventListPanel --|> UiPart
EventCard --|> UiPart
SingleEventPanel --|> UiPart
StatusBarFooter -up-|> UiPart
HelpWindow -down-|> UiPart

MemberCard .up.> Model
EventCard .down.> Model
UiManager -right-> Logic
MainWindow -left-> Logic

HelpWindow -[hidden]down- CommandBox
CommandBox -[hidden]down- ResultDisplay
ResultDisplay -[hidden]down- StatusBarFooter
ResultDisplay -[hidden]right- UiPart
StatusBarFooter -[hidden]right- UiPart

MemberCard -[hidden]up- UiPart
MemberCard -[hidden]left- CommandBox
EventCard -[hidden]left- UiPart
SingleEventPanel -[hidden]down- MemberListPanel

MainWindow -[hidden]-|> UiPart
@enduml
